## Numpy 
Numpy is short for Numeric Python, which prodives an alternative to a regualar python list: the Numpy **Array**.  
https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html

## Arrays
An array is sort of like a table of cells in Excel, but not exactly like a matrix in MATLAB. Its advantage over the list is that it allows us to make calculations over entire arrays, unlike lists. This is because with arrays, Python can recognize individual values in the array, rather than seeing a list as an entire object itself.  

  
For example:

In [22]:
import numpy as np

height_list = [1.65, 1.71, 1.76, 1.79, 1.83]
weight_list = [67.3, 58.9, 73.4, 75.9, 79.1]

height_array = np.array(height_list) # Convert an existing list into a 1D array
weight_array = np.array([67.3, 58.9, 73.4, 75.9, 79.1]) # Or key in the values yourself

bmi = weight_array/height_array**2 # We couldnt do this with regular lists
print(bmi)

[ 24.71992654  20.14294997  23.69576446  23.68839924  23.61969602]


Remember, an array is simply a newly defined Python **type** or **class** of object with its own **attributes**, **methods** and **behaviour**. As an example, the + symbol provides different bevahiours from lists and arrays

In [23]:
# Adding lists together joins both lists to create a new list
height_list = [1.65, 1.71, 1.76, 1.79, 1.83]
weight_list = [67.3, 58.9, 73.4, 75.9, 79.1]

print(weight_list+height_list)

[67.3, 58.9, 73.4, 75.9, 79.1, 1.65, 1.71, 1.76, 1.79, 1.83]


In [24]:
# Adding arrays together adds the corresponding values in each array to give a new array
height_array = np.array(height_list)
weight_array = np.array(weight_list)

print(weight_array+height_array)

[ 68.95  60.61  75.16  77.69  80.93]


## Remarks
Numpy arrays can only contain objects of the same type, if multiple types are specified into a single array, Numpy will automatically convert them to a uniform type. This is known as type coercion.

In [25]:
np.array([1.0,4,"is", True]) #Numpy automatically converts our ints, floats and bools into strings.

array(['1.0', '4', 'is', 'True'], 
      dtype='<U32')

## Array Subsetting  
The are multiple ways to select individual objects in arrays

In [26]:
# We can use square bracket to call objects at an index location, just like with lists
height_array = np.array([1.65, 1.71, 1.76, 1.71, 1.83])
print(height_array[2])

1.76


## Boolean Numpy Arrays

In [27]:
# We can even use the >, >=, <=, <, ==, != fuctions to return if objects meet a criteria
height_array = np.array([1.65, 1.71, 1.76, 1.71, 1.83])
tall = height_array > 1.75
onesevenone = height_array == 1.71

print(tall)
print(onesevenone)
# If we want to call only those values that are True (meeting the criteria) in the array we use
print(height_array[tall])
print(height_array[height_array == 1.71])

[False False  True False  True]
[False  True False  True False]
[ 1.76  1.83]
[ 1.71  1.71]


## 2D Arrays  
So far we have only looked at 1 dimensional arrays, but we can create arrays with as many dimensions as we want. These can be thought of as tables with rows and columns, or even as a matrix!  
  
Here's an example of a 2D Numpy array:

In [28]:
two_d = np.array([[1,2,3,4,5,6,7,8],[2,4,6,8,10,12,14,16]]) #Almost like an improved "list of lists"
print(two_d) # What beautiful matrix-like structure

[[ 1  2  3  4  5  6  7  8]
 [ 2  4  6  8 10 12 14 16]]


In [29]:
two_d.shape # We can call the shape attibute of the array, and see that it has 2 rows and 8 columns

(2, 8)

## Subsetting 2D Arrays
Similar to how we selected and object in a list of lists, to call an object in an array, we first specify the row, then the column with square brackets, or as a pair of indexes seperated by a comma

In [30]:
two_d # Calling the entire array

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  4,  6,  8, 10, 12, 14, 16]])

In [31]:
two_d[0] # Calling an entire row

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
two_d[0][6] # Calling object in row index 0, column index 6

7

In [33]:
two_d[0,6] # Calling object in row index 0, column index 6

7

We can even call a subset of the entire array by specifying which parts of the array we want

In [34]:
two_d[:,5:8] # Calling both rows, column index 5 to 8

array([[ 6,  7,  8],
       [12, 14, 16]])

In [35]:
two_d[1,:] # Calling row index 1, all columns

array([ 2,  4,  6,  8, 10, 12, 14, 16])

## 2D Arithmetic
Numpy is able to perform all array calculations element-wise. For 2D Numpy arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.

In [36]:
array1 = np.array([[10,10,10,10],[10,10,10,10],[10,10,10,10]])
print(array1)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [44]:
array_addition = array1+np.array([10,10,10,10])
print(array_addition)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


In [41]:
array_multiplication = array1 * 3
print(array_multiplication)

[[30 30 30 30]
 [30 30 30 30]
 [30 30 30 30]]
