## Packages
A Python **package** can be thought of as a folder of prewritten Python **scripts** (or modules) aimed at solving particular problems. Packages specify new **functions**, **methods**, and **object types** or **classes**. There are literally thousands of Python packages available on the internet.  

Some of the more used ones are:  
  
* ### Numpy
Allows us to work with arrays in Python

* ### Math
Gives us some useful math functions and constants like math.pi and radians(angle)

* ### Matplotlib
Useful for Data Visualization

* ### Scikit-learn
for predefined machine learning models  

## Installing Packages with pip

In [ ]:
pip3 install numpy #enter this into terminal

## Importing Packages into a Python Script
We need to import packages at the start of out script before we do anything else, so that Python knows all the new stuff we are using.

In [8]:
# Importing the installed numpy package as np, so that we can call it with the shortcut np
import numpy as np

# Now we can use the array class objects defined by the .py scripts in the numpy package
np.array([1,2,3])

array([1, 2, 3])

In [10]:
# If we only want to import a single function from a package we use this code instead
from numpy import array # Let's be clear that this is not the most conveinient method.

# As you can see, since we have only imported a function into our script, there is no need to call np
# The array function itself acts as if it exists in out own script, rather than in the numpy package.
array([1,2,3])

array([1, 2, 3])